// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3HE0fFEuJ3LgPNlkXC4dGToarcI1pdoQ',
    appId: '1:882094651598:web:ad7c9b58f6477b328fb89f',
    messagingSenderId: '882094651598',
    projectId: 'theconceptcure',
    authDomain: 'theconceptcure.firebaseapp.com',
    databaseURL: 'https://theconceptcure-default-rtdb.firebaseio.com',
    storageBucket: 'theconceptcure.appspot.com',
    measurementId: 'G-24G8GLYSP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_zyZexdJ58Q7mXdj41Qm92bu21YlwHrA',
    appId: '1:882094651598:android:29fda17366a5e25e8fb89f',
    messagingSenderId: '882094651598',
    projectId: 'theconceptcure',
    databaseURL: 'https://theconceptcure-default-rtdb.firebaseio.com',
    storageBucket: 'theconceptcure.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4M7BGZYizSRKIAicvrdRFP2GvTQ3hhC4',
    appId: '1:882094651598:ios:5a6dbc3839df75208fb89f',
    messagingSenderId: '882094651598',
    projectId: 'theconceptcure',
    databaseURL: 'https://theconceptcure-default-rtdb.firebaseio.com',
    storageBucket: 'theconceptcure.appspot.com',
    androidClientId: '882094651598-u3g6oo7f0aur59qnn7525q3c2meb3qle.apps.googleusercontent.com',
    iosClientId: '882094651598-51vdt0cg46for861nrj92tjsvk5910dg.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatBot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4M7BGZYizSRKIAicvrdRFP2GvTQ3hhC4',
    appId: '1:882094651598:ios:0415d574ada8939d8fb89f',
    messagingSenderId: '882094651598',
    projectId: 'theconceptcure',
    databaseURL: 'https://theconceptcure-default-rtdb.firebaseio.com',
    storageBucket: 'theconceptcure.appspot.com',
    androidClientId: '882094651598-u3g6oo7f0aur59qnn7525q3c2meb3qle.apps.googleusercontent.com',
    iosClientId: '882094651598-edhqkoa3dko20snj5qnsiluf765crlom.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatBot.RunnerTests',
  );
}
